server {
    listen 443 ssl;
    server_name __TS_HOSTNAME__;

    ssl_certificate     /etc/nginx/certs/__TS_HOSTNAME__.crt;
    ssl_certificate_key /etc/nginx/certs/__TS_HOSTNAME__.key;

    root /home/pi/my-secretary/frontend/dist;
    index index.html;

    location /api/ {
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}

server {
    listen 80;
    server_name __TS_HOSTNAME__;
    return 301 https://$host$request_uri;
}
