"""add calendar_events and calendar_sync

Revision ID: 8f8f43ed5ce5
Revises: 0002
Create Date: 2026-06-12 22:22:39.527496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f8f43ed5ce5'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_events',
    sa.Column('google_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('start_dt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_dt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('all_day', sa.Boolean(), nullable=False),
    sa.Column('start_date', sa.String(length=10), nullable=True),
    sa.Column('cancelled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('google_id')
    )
    op.create_table('calendar_sync',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credentials_json', sa.Text(), nullable=True),
    sa.Column('sync_token', sa.String(length=500), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calendar_sync')
    op.drop_table('calendar_events')
    # ### end Alembic commands ###
